apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tools

resources:
  - ../../../../base/omni-tools

patches:
  - path: patches/ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: vx-home-tools
  environment: vx-home
